debug: true

server:
  port: 9602

spring:
  profiles:
    active:

ustra:
  core:
    cache:
      map:
        additional-cache-names: USTRA-TEST-CACHE
      caffeine:
        caffeine-test:
          maximum-size: 200
          initial-capacity: 100
          # refresh-seconds: 600
          expire-after-write-seconds: 1800
          expire-after-access-seconds: 1800
        #eh:
        #  eh-test:
        #    config-location: classpath:/ehcache.xml
  data:
    procedure-manager:
      enabled: true
    datasource:
      default-datasource-name: rds1
      datasources:
        rds1:
          url: jdbc:log4jdbc:sqlserver://framework-sqlserver.c0uiyan5ae24.ap-northeast-2.rds.amazonaws.com:1433;databaseName=USTRA_FW_SPL
          driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
          username: ENC(p6rIPoShJklFLPxHKNJYFLooNCd2xnkayNZ2f+GexyA17qEMS77u8g==)
          password: ENC(ohS/a1/Q/lKriwUq3rqJqht76fQ0Bnge)
    logging:
       interfaces:
          enabled: true
  mvc:
    view:
      type: STATIC_THYEMELEAF
   
  management:
    bo:
      app:
        maximum-menu-depth: 10
      batch:
        manager-endpoint: http://localhost:9602/api/batch

  batch:
    manager:
      enabled: true
      id: M01
    worker:
      enabled: true
      id: W01
    logger:
      max-days: 10
#      path-pattern: "/Users/wisehouse/workspace/GSITM/U.STRA TUTORIAL/logs/${taskId}/${taskInstanceId}.log"
      path-pattern: "C:\\logs\\${taskId}\\${taskInstanceId}.log"
      log-pattern: "%d{yyyy-MM-dd HH:mm:ss} [%-5p] %c.%M\\(%F:%L\\) : %m%n"
